### ISSUE TITLE
Fix incorrect variable names for better readability

### ISSUE THREAD

**Issue by 07Vaishnavi-Singh** [Cork-Technology/Depeg-swap#113]
https://github.com/orgs/Cork-Technology/projects/1/views/1?pane=issue&itemId=81860758

### Fix variable names with typo errors
Refer this issue from sherlock audit : [sherlock issue link](https://github.com/sherlock-audit/2024-08-cork-protocol-judging/issues/271)
- [ ] Fix incorrect variable and function names
- [ ] Also fix same in testcases

**Comment by ziankork** [comment]
fixed in #91. closing this
