### ISSUE TITLE
Remove unused/non-useful part of code

### ISSUE THREAD

**Issue by 07Vaishnavi-Singh** [Cork-Technology/Depeg-swap#115]
https://github.com/orgs/Cork-Technology/projects/1/views/1?pane=issue&itemId=81881406

### Remove parts of code which are not useful and safe to remove
Reference : [Sherlock issue link](https://github.com/sherlock-audit/2024-08-cork-protocol-judging/issues/306)
- [x] Remove extra code from VaultPoolLib.sol

**Comment by siddhpurakaran** [comment]
Removed unused parts of code as part of preparing code for cantina audit
