### ISSUE TITLE
Remove unused imports

### ISSUE THREAD

**Issue by 07Vaishnavi-Singh** [Cork-Technology/Depeg-swap#116]
https://github.com/orgs/Cork-Technology/projects/1/views/1?pane=issue&itemId=81889181 

### Remove unused imports from contracts
Refernce : [Sherlock issue link](https://github.com/sherlock-audit/2024-08-cork-protocol-judging/issues/269)

- [x] Remove unused imports from contracts

**Comment by siddhpurakaran** [comment]
Removed all unused imports from contracts and refactored it as part of audit scope preparations
