### ISSUE TITLE
Use !0 instead of >0 for unsigned integer comparisons

### ISSUE THREAD

**Issue by yusak-cork** [Cork-Technology/Depeg-swap#118]
https://github.com/orgs/Cork-Technology/projects/1/views/1?pane=issue&itemId=81889635

Reference link : [Sherlock issue link](https://github.com/sherlock-audit/2024-08-cork-protocol-judging/issues/282)

- [ ] Use !0 instead of >0 for unsigned integer comparisons

**Comment by ziankork** [comment]
closing this as we're moving to uni v4
