### ISSUE TITLE
Verify the smart contracts deployed on Sepolia Etherscan

### ISSUE THREAD

**Issue by computerpoet** [Cork-Technology/Depeg-swap#136]
https://docs.cork.tech/testnet-trading-competition-ui-tutorial/contract-addresses

**Comment by siddhpurakaran** [comment]
@07Vaishnavi-Singh 
Please verify below list of smart contract on sepolia 

  CETH                            :  0x93D16d90490d812ca6fBFD29E8eF3B31495d257D
  bsETH                           :  0xb194fc7C6ab86dCF5D96CF8525576245d0459ea9
  lbETH                           :  0xF24177162B1604e56EB338dd9775d75CC79DaC2B
  wamuETH                         :  0x38B61B429a3526cC6C446400DbfcA4c1ae61F11B
  mlETH                           :  0xCDc1133148121F43bE5F1CfB3a6426BbC01a9AF6
  Asset Factory Implementation    :  0x92D8b534237C5Be34753b975D53a14b494b96Ef4
  Asset Factory                   :  0xbdfc069558B9d87Df40f9A4876Fa7c52f6492788
  Cork Config                     :  0x8c996E7f76fB033cDb83CE1de7c3A134e17Cc227
  Flashswap Router Implementation :  0xE6F58Dd84869542d7Ec1c0153417E20Fa220B63d
  Flashswap Router Proxy          :  0x6629e017455CB886669e725AF1BC826b65cB6f24
  Univ2 Factory                   :  0x8fD48F4ec9cB04540134c02f4dAa5f68585c3936
  Univ2 Router                    :  0x363E8886E8FF30b6f6770712Cf4e758e2Bf3E353
  ModuleCore Router Implementation :  0x26De252a30812645960846cEA402E4B34A8eaD89
  Module Core                     :  0xe56565c208d0a8Ca28FB632aD7F6518f273B8B9f

Note : currently most of contract code is updated so you have to used at time of deployement so please use commits around  trading competition start date

**Comment by siddhpurakaran** [comment]
Below list of contracts got verified
  CETH                                               :  0x93D16d90490d812ca6fBFD29E8eF3B31495d257D
  bsETH                                             :  0xb194fc7C6ab86dCF5D96CF8525576245d0459ea9
  lbETH                                              :  0xF24177162B1604e56EB338dd9775d75CC79DaC2B
  wamuETH                                      :  0x38B61B429a3526cC6C446400DbfcA4c1ae61F11B
  mlETH                                             :  0xCDc1133148121F43bE5F1CfB3a6426BbC01a9AF6
  Asset Factory Implementation  :  0x92D8b534237C5Be34753b975D53a14b494b96Ef4
  Asset Factory                                :  0xbdfc069558B9d87Df40f9A4876Fa7c52f6492788
  Cork Config                                   :  0x8c996E7f76fB033cDb83CE1de7c3A134e17Cc227
  Flashswap Router Implementation :  0x3687694873bA2A746609fbd3B33CDb69b30BA602
  Flashswap Router Proxy             :  0x6629e017455CB886669e725AF1BC826b65cB6f24
  ModuleCore Router Implementation:  0xb0926d56e9C9A72A1412B54d5555782cCD56124F
  ModuleCore Router Proxy         :  0xe56565c208d0a8Ca28FB632aD7F6518f273B8B9f

Note : 
1. Most of events in protocol are being emmited from moduleCore and FlashswapRouter contracts so start from there
2. Haven't verified below 2 uniswap contracts, but let me know if it needed then we will do it
    a. Univ2 Factory                   :  0x8fD48F4ec9cB04540134c02f4dAa5f68585c3936
    b. Univ2 Router                    :  0x363E8886E8FF30b6f6770712Cf4e758e2Bf3E353

**Comment by computerpoet** [comment]
Could you verify the 2 uniswap contracts ?
