### ISSUE TITLE
Hedged Unit Wrapper Contract

### ISSUE THREAD

**Issue by computerpoet** [Cork-Technology/Depeg-swap#147]
Deprecated Roadmap Link
https://github.com/users/Corktech/projects/2/views/1?pane=issue&itemId=69994471

As described here:
https://www.notion.so/corkfi/Hedged-Unit-c874d0754e034ff6aa272a7e9bad512e

Make sure rollover spec is supported well here

- [x] complete base for hedgewrapper contract
- [x] research cowswap liquidation implementations 
- [x] implement liquidator contract with cowswap 
- [x] Prepare doc (in progress)
- [ ] test depeg scenarios

**Comment by siddhpurakaran** [comment]
1. Added base Hedge Unit contract(with simple mint-dissolve functions)
2. Reviewed whole cowswap contracts and architecture
3. Implemented Liquidator contract with cowswap

**Comment by siddhpurakaran** [comment]
We have to integrate new Universal liquidation mechanism in this Hedge Units

**Comment by siddhpurakaran** [comment]
Preparing final spec for integrating universal liquidity mechanism by discussing with team

**Comment by siddhpurakaran** [comment]
Completed and merged
