### ISSUE TITLE
Quantstamp Bug fixes

### ISSUE THREAD

**Issue by siddhpurakaran** [Cork-Technology/Depeg-swap#148]

**Comment by siddhpurakaran** [comment]
- [ ] fix issues no 1 to 7
- [ ] fix issue no 8 to 15

**Comment by 07Vaishnavi-Singh** [comment]
- Created seperate branches for each issue 
- Backlog Cork-2 ( Needs some discussion if there needs to be architectural change or a new feature )
- In Progress Cork-4 (Should be done by tonight just need the way it should be implemented which karan is work on whenever he gets free)

**Comment by siddhpurakaran** [comment]
- [x] Added proper validations for insuring that users can not bypass permit by sending empty signature or 0 in deadline
- [ ] Add function hash  in signature (I tried to implement it but it will need to use modified ERC20Permit contract instead of openzeppeline's default, so asked quantstamp for advice)

**Comment by siddhpurakaran** [comment]
Sent PRs for review to quantstamp : https://docs.google.com/document/d/1h_Hr58Bdzsp5P3JrnY-PiJBeGiCiri1bAqexFmDexCM/edit?usp=sharing

**Comment by siddhpurakaran** [comment]
Completed second round of fixes and sent them to quantstamp team for review
