### ISSUE TITLE
Flash Swaps Permit Support

### ISSUE THREAD

**Issue by ziankork** [Cork-Technology/Depeg-swap#33]
# Overview
After [flash swap](#28) is merged, it enables buying/selling DS facilitated via flash swap to AMM. But currently, it doesn't support permit functionality yet. Considering when selling, DS always has permit functionality and adding it for buying DS will also provide support for RA that also support permit.

# Tasks List

- [x] Add permit support for RA(and add checks if it supports permit) when buying DS.
- [x] Add permit support for DS when selling DS.

**Comment by siddhpurakaran** [comment]
Completed Here : https://github.com/Cork-Technology/Depeg-swap/pull/34/files
