### ISSUE TITLE
Price feed bot is fed wrong information

### ISSUE THREAD

**Issue by computerpoet** [Cork-Technology/Depeg-swap#79]
![Image](https://github.com/user-attachments/assets/aa3eaed3-d40c-49d4-9b35-01d320f9b35e)

![Image](https://github.com/user-attachments/assets/e1d461c1-0dbc-414c-bd61-68a72ab6f2f7)

**Comment by computerpoet** [comment]
How is the price calculated ?

**Comment by ziankork** [comment]
seems like we've solved the issue, will close this for now.
